name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          go build -o 8ball .

      - name: Copy binary to DigitalOcean droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "8ball"
          target: "~/"

      - name: Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill gotty || true
            nohup gotty -w ~/8ball > /dev/null 2>&1 &          
