name: Deploy Go Application over SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            pkill gotty || true
            cd ~/magic-8-ball
            rm 8ball
            git pull
            go build -o 8ball .
            sudo systemctl restart gotty.service
